name: Storybook PR Checks
on:
  pull_request:
    branches:
      - master

jobs:
  smartui-gihub-action:
    name: Execute Storybook build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Find Last CommitId
      run: |
        API_HOST=https://api.github.com
        # Check out the PR branch
        git checkout $GITHUB_HEAD_REF
        # Get the commit ID of the last commit
        COMMIT_ID=$(git rev-parse HEAD)
        echo "Last commit ID of PR: $COMMIT_ID"
        GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
        echo "GITHUB_URL: $GITHUB_URL"
        echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV
   
    - name: Install Dependencies
      run: |
        npm install
        npm install @lambdatest/smartui-storybook -g

    - name: Execute storybook build1
      run: |
        export PROJECT_TOKEN=1639932#41216695-903c-4ea3-9f57-901a14a0fee1#Telus-sb-githubcheck
        smartui --version
        smartui storybook ./story-dashlane --config .smartui.json
        
    - name: Execute storybook build2
      run: |
        export PROJECT_TOKEN=1639932#d67104f4-43f7-43f0-9d11-2dcd47a7e00b#Telus-sb-githubcheck-2
        smartui --version
        smartui storybook ./story-telus --config .smartui.json














       




