name: Storybook PR Checks
on:
  pull_request:
    branches:
      - master

jobs:
  smartui-gihub-action:
    name: Execute Storybook build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Find Last CommitId
      run: |
        API_HOST=https://api.github.com
        # Check out the PR branch
        git checkout $GITHUB_HEAD_REF
        # Get the commit ID of the last commit
        COMMIT_ID=$(git rev-parse HEAD)
        echo "Last commit ID of PR: $COMMIT_ID"
        GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
        echo "GITHUB_URL: $GITHUB_URL"
        echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV
   
    - name: Install Dependencies
      run: |
        npm install
        npm install @lambdatest/smartui-storybook -g

    - name: Execute storybook build1
      run: |
        export PROJECT_TOKEN=33244476#e2fbb54c-dcab-4e85-8f21-6761e319da32#Telus-storybook-githubpr
        smartui --version
        smartui storybook ./story-dashlane --config .smartui.json --env stage --force-rebuild
        
    - name: Execute storybook build2
      run: |
        export PROJECT_TOKEN=33244476#91c4b436-b338-45a6-a8b4-f4b068d57495#Telus-storybook-githubpr-2
        smartui --version
        smartui storybook ./story-dashlane --config .smartui.json --env stage --force-rebuild

    - name: Execute storybook build3
      run: |
        export PROJECT_TOKEN=33244476#8edaea40-ba58-48a9-a2a4-1117dacc33f2#Telus-storybook-githubpr-3
        smartui --version
        smartui storybook ./story-dashlane --config .smartui.json --env stage --force-rebuild


       




